<script lang="ts">
  import { onMount } from 'svelte';
  import ActionButton from '../components/ActionButton.svelte';
  import AppStatusBadge from '../components/AppStatusBadge.svelte';
  import ConfigPreview from '../components/ConfigPreview.svelte';
  import EmptyState from '../components/EmptyState.svelte';
  import SectionHeader from '../components/SectionHeader.svelte';
  import StatusCard from '../components/StatusCard.svelte';
  import { deployNode, deployStatic, getApps, getSystemdPreview } from '../lib/api';
  import type { AppRecord, DeployResult, SystemdPreview } from '../lib/types';

  let apps: AppRecord[] = [];
  let selectedId = '';
  let sourcePath = '';
  let error = '';
  let message = '';
  let deploying = false;
  let result: DeployResult | null = null;
  let systemdPreview: SystemdPreview | null = null;

  $: selectedApp = apps.find((app) => app.id === selectedId);

  onMount(loadApps);

  async function loadApps() {
    try {
      apps = await getApps();
      selectedId = apps[0]?.id ?? '';
      await loadPreview();
    } catch (err) {
      error = err instanceof Error ? err.message : 'Deploy request failed';
    }
  }

  async function loadPreview() {
    if (!selectedId) return;
    try {
      systemdPreview = await getSystemdPreview(selectedId);
    } catch {
      systemdPreview = null;
    }
  }

  async function submitDeploy() {
    if (!selectedApp) return;
    error = '';
    message = '';
    result = null;
    deploying = true;

    try {
      result = selectedApp.runtime === 'node'
        ? await deployNode(selectedApp.id, { source_path: sourcePath })
        : await deployStatic(selectedApp.id, { source_path: sourcePath });
      message = 'Deployment completed.';
      await loadApps();
    } catch (err) {
      error = err instanceof Error ? err.message : 'Deployment failed';
    } finally {
      deploying = false;
    }
  }
</script>

<div class="page">
  {#if error}<p class="error">{error}</p>{/if}
  {#if message}<p class="success">{message}</p>{/if}

  <section class="panel">
    <SectionHeader
      eyebrow="Deployment"
      title="Run local source deployment"
      description="Source path must already exist on the server. Git/upload are not implemented."
    />

    <form class="deploy-form" on:submit|preventDefault={submitDeploy}>
      <select class="field" bind:value={selectedId} on:change={loadPreview} required>
        {#each apps as app}
          <option value={app.id}>{app.name} · {app.runtime}</option>
        {/each}
      </select>
      <input class="field" bind:value={sourcePath} placeholder="/srv/example-site/dist" required />
      <button class="primary" type="submit" disabled={deploying || !selectedApp}>
        {deploying ? 'Deploying...' : 'Deploy'}
      </button>
    </form>

    {#if selectedApp && selectedApp.runtime !== 'static' && selectedApp.runtime !== 'node'}
      <p class="warning">Only static and node adapters are implemented right now.</p>
    {/if}
  </section>

  <ConfigPreview preview={systemdPreview} />

  {#if result}
    <section class="panel">
      <SectionHeader eyebrow="Result" title="Latest deployment" description="Generated by backend adapter." />
      <div class="metric-grid">
        <StatusCard label="Status" value={result.status} />
        <StatusCard label="Release" value={result.release_id} />
        <StatusCard label="Package manager" value={result.package_manager ?? 'n/a'} />
      </div>
      <pre>{result.release_path}
{result.current_path}
{result.deploy_log_path}</pre>
    </section>
  {/if}

  <section class="panel">
    <div class="toolbar">
      <SectionHeader eyebrow="Targets" title="Deployable apps" description="Metadata from SQLite." />
      <ActionButton href="/apps" label="Create app" variant="primary" />
    </div>

    {#if apps.length}
      <div class="deploy-list">
        {#each apps as app}
          <div class="deploy-row">
            <span>
              <strong>{app.name}</strong>
              <small>{app.runtime} · /opt/lightpanel/data/apps/{app.name}</small>
            </span>
            <AppStatusBadge status={app.status} />
          </div>
        {/each}
      </div>
    {:else}
      <EmptyState title="No deployment targets" description="Create app metadata before using adapters." />
    {/if}
  </section>
</div>

<style>
  .deploy-form {
    display: grid;
    gap: var(--space-3);
    grid-template-columns: 240px 1fr auto;
  }

  .deploy-list {
    display: grid;
    gap: 10px;
  }

  .deploy-row {
    align-items: center;
    border-bottom: 1px solid var(--border);
    display: flex;
    justify-content: space-between;
    padding: 12px 0;
  }

  span {
    display: grid;
    gap: 4px;
  }

  small {
    color: var(--text-muted);
  }

  button {
    border: 1px solid var(--border);
    border-radius: var(--radius-sm);
    min-height: 36px;
    padding: 0 14px;
  }

  .primary {
    background: var(--accent);
    color: #03120c;
    font-weight: 700;
  }

  .success {
    color: var(--green);
  }

  .warning {
    color: var(--amber);
  }

  pre {
    color: var(--text-muted);
    white-space: pre-wrap;
  }
</style>
